project_id = "oxwbeahwldxtwfezubdm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://100in.app"
additional_redirect_urls = ["https://localhost:3000", "https://100in.app", "https://9a7df55c-cf11-4367-ab0d-5ed7f247add9.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.send-notification]
verify_jwt = false

[functions.error-tracking]
verify_jwt = false

[functions.analyze-game-stats]
verify_jwt = true

[functions.chat-relay]
verify_jwt = true