// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxwbeahwldxtwfezubdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94d2JlYWh3bGR4dHdmZXp1YmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTM1OTIsImV4cCI6MjA2OTI2OTU5Mn0.n1vwlnzdFnyV_kEqmqYAYEqUf1C4YuqTAGnL4YQ1oV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});